# Generated by Django 2.2.9 on 2020-07-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
    ]
