# Generated by Django 2.2.9 on 2020-07-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200709_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='college',
            field=models.CharField(default='信息工程学院', max_length=64, verbose_name='所属学院'),
            preserve_default=False,
        ),
    ]
